name: deploy Core from artifacts for other services to run acceptance test
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      aws-region:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      artifact-bucket-name:
        required: true
      app-name:
        required: true
      tf-bucket:
        required: true
jobs:
  deploy-core-infrastructure-from-artifact:
    name: Deploy core.infrastructure from artifact to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Download Artifacts
        env:
          ARTIFACT_BUCKET_NAME: ${{ secrets.artifact-bucket-name }}
          ENVIRONMENT: prod
          CONTEXT: core
        run: |
          aws s3 cp s3://"$ARTIFACT_BUCKET_NAME"/"$ENVIRONMENT"/"$CONTEXT"/infrastructure.zip ./infrastructure.zip
          unzip infrastructure.zip
          rm infrastructure.zip

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./_repo/

      - name: Apply Terraform
        uses: ./_repo/.github/actions/core/infrastructure/apply
        with:
          infrastructure-directory: ./
          app-name: ${{ secrets.app-name }}
          region: ${{ secrets.aws-region }}
          tf-bucket: ${{ secrets.tf-bucket }}
          frontend-bucket: ${{ secrets.app-name }}-${{ inputs.environment }}
          resource-sharing-bucket: ${{ secrets.app-name }}-resource-sharing-${{ inputs.environment }}
          environment: ${{ inputs.environment }}
